openapi: 3.0.1
info:
  title: BoomFi Rates API
  version: 1.0.0
  description: API for retrieving quotes for purchasing cryptocurrency using fiat currencies.
servers:
  - url: https://capi-test.boomfi.xyz/v1
paths:
  /ramp/quote:
    get:
      summary: Get Ramp Quotes
      description: This endpoint provides a quote for buying a specified amount of cryptocurrency using fiat currency. The user needs to specify the fiat currency, the cryptocurrency token address, and other relevant parameters to get a quote.
      parameters:
        - name: sell_currency
          in: query
          required: true
          description: The fiat currency you want to sell. At the moment only EUR is supported.
          schema:
            type: string
            enum:
              - EUR
        - name: buy_token
          in: query
          required: true
          description: The token address of the cryptocurrency you want to buy. Find the available tokens on [swap.boomfi.xyz](swap.boomfi.xyz).
          schema:
            type: string
        - name: buy_currency
          in: query
          required: true
          description: The symbol of the cryptocurrency you want to buy (for easier debugging).
          schema:
            type: string
        - name: payment_method
          in: query
          required: true
          description: The payment method. Currently, only "Card" is supported.
          schema:
            type: string
            enum:
              - Card
        - name: chain_id
          in: query
          required: true
          description: The chain ID of the blockchain on which you would like to buy the token. Refer to the documentation for the supported chain IDs.
          schema:
            type: integer
        - name: sell_amount
          in: query
          required: false
          description: The amount of fiat currency you want to sell. ⚠️ Required if `buy_amount` not informed. ⚠️
          schema:
            type: number
        - name: buy_amount
          in: query
          required: false
          description: The amount of cryptocurrency you want to buy. ⚠️ Required if `sell_amount` not informed. ⚠️
          schema:
            type: number
      responses:
        '200':
          description: A successful response containing the quote details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      buy_currency:
                        type: string
                        description: The symbol of the cryptocurrency being bought.
                        example: USDC
                      buy_amount:
                        type: string
                        description: The amount of cryptocurrency that will be received.
                        example: "72.22"
                      sell_currency:
                        type: string
                        description: The fiat currency used for the purchase.
                        example: EUR
                      sell_amount:
                        type: string
                        description: The amount of fiat currency used in the transaction.
                        example: "100"
                      payment_method:
                        type: string
                        description: The payment method used in the transaction.
                        example: Card
                      quote_time:
                        type: string
                        format: date-time
                        description: The time when the quote was generated.
                        example: "2024-05-23T21:13:24.531851848Z"
                      expiry:
                        type: string
                        format: date-time
                        description: The expiration time of the quote.
                        example: "2024-05-23T21:13:34.531851848Z"
                      rate:
                        type: string
                        description: The exchange rate applied in the quote.
                        example: "1.035"
                      fees:
                        type: object
                        properties:
                          fee_ccy:
                            type: string
                            description: The currency in which the fees are charged.
                            example: EUR
                          network_fee:
                            type: string
                            description: The fee charged by the network.
                            example: "29.231662792647756526654796064"
                          boomfi_fee:
                            type: string
                            description: The fee charged by BoomFi.
                            example: "1"
                          total_fee:
                            type: string
                            description: The total fees charged.
                            example: "30.231662792647756526654796064"
                      quote_amount:
                        type: string
                        description: The total amount quoted for the transaction.
                        example: "100"
                      settlement_ccy:
                        type: string
                        description: The currency in which the settlement will occur.
                        example: USDC
                      settlement_chain_id:
                        type: integer
                        description: The chain ID of the blockchain where the settlement will occur.
                        example: 1
                      settlement_token_address:
                        type: string
                        description: The token address of the cryptocurrency being bought.
                        example: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
                      session:
                        type: string
                        description: The session identifier for the transaction.
                        example: "abc123xyz456def789ghi012jkl345mno678pqr901stu234vwx567yz890"
        '400':
          description: Invalid request. One or more parameters might be missing or incorrect.
        '500':
          description: Internal server error. Something went wrong on the server side.
  /ramp/currencies:
    get:
      description: Retrieve a list of supported currencies with their details.
      summary: Get supported currencies
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: "A mapping of currency symbols to their details."
                    properties:
                      BNB:
                        type: object
                        description: "Details for BNB currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: BNB
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: BNB
                          tokens:
                            type: array
                            description: "List of tokens associated with this currency."
                            items:
                              type: object
                              properties:
                                chain_id:
                                  type: string
                                  description: "The chain ID where the token is available."
                                  example: '56'
                                name:
                                  type: string
                                  description: "The name of the token."
                                  example: BNB
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Digital
                      DAI:
                        type: object
                        description: "Details for DAI currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: Dai
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: DAI
                          tokens:
                            type: array
                            description: "List of tokens associated with this currency."
                            items:
                              type: object
                              properties:
                                address:
                                  type: string
                                  description: "The token address."
                                  example: '0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3'
                                chain_id:
                                  type: string
                                  description: "The chain ID where the token is available."
                                  example: '56'
                                name:
                                  type: string
                                  description: "The name of the token."
                                  example: Dai
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Digital
                      ETH:
                        type: object
                        description: "Details for ETH currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: Ethereum
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: ETH
                          tokens:
                            type: array
                            description: "List of tokens associated with this currency."
                            items:
                              type: object
                              properties:
                                chain_id:
                                  type: string
                                  description: "The chain ID where the token is available."
                                  example: '1'
                                name:
                                  type: string
                                  description: "The name of the token."
                                  example: ETH
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Digital
                      EUR:
                        type: object
                        description: "Details for EUR currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: Euro
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: EUR
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Fiat
                      GBP:
                        type: object
                        description: "Details for GBP currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: British Pound Sterling
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: GBP
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Fiat
                      USD:
                        type: object
                        description: "Details for USD currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: US Dollar
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: USD
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Fiat
                      USDT:
                        type: object
                        description: "Details for USDT currency."
                        properties:
                          name:
                            type: string
                            description: "The name of the currency."
                            example: Tether USDt
                          symbol:
                            type: string
                            description: "The symbol of the currency."
                            example: USDT
                          type:
                            type: string
                            description: "The type of the currency (e.g., Digital, Fiat)."
                            example: Digital
                          tokens:
                            type: array
                            description: "List of tokens associated with this currency."
                            items:
                              type: object
                              properties:
                                address:
                                  type: string
                                  description: "The token address."
                                  example: '0x55d398326f99059fF775485246999027B3197955'
                                chain_id:
                                  type: string
                                  description: "The chain ID where the token is available."
                                  example: '56'
                                name:
                                  type: string
                                  description: "The name of the token."
                                  example: Tether USDt
              examples:
                sample:
                  value:
                    data:
                      BNB:
                        name: BNB
                        symbol: BNB
                        tokens:
                        - chain_id: '56'
                          name: BNB
                        type: Digital
                      DAI:
                        name: Dai
                        symbol: DAI
                        tokens:
                        - address: '0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3'
                          chain_id: '56'
                          name: Dai
                        - address: '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063'
                          chain_id: '137'
                          name: Dai
                        type: Digital
                      ETH:
                        name: Ethereum
                        symbol: ETH
                        tokens:
                        - chain_id: '1'
                          name: ETH
                        - chain_id: '42161'
                          name: ETH
                        type: Digital
                      EUR:
                        name: Euro
                        symbol: EUR
                        type: Fiat
                      GBP:
                        name: British Pound Sterling
                        symbol: GBP
                        type: Fiat
                      USD:
                        name: US Dollar
                        symbol: USD
                        type: Fiat
                      USDT:
                        name: Tether USDt
                        symbol: USDT
                        type: Digital
                        tokens:
                        - address: '0x55d398326f99059fF775485246999027B3197955'
                          chain_id: '56'
                          name: Tether USDt
                        - address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F'
                          chain_id: '137'
                          name: Tether USDt
                        - address: '0xdAC17F958D2ee523a2206206994597C13D831ec7'
                          chain_id: '1'
                          name: Tether USDt
                        - address: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB'
                          chain_id: '1399811149'
                          name: Tether USDt
                        - address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'
                          chain_id: '-200'
                          name: Tether USD
                        - address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'
                          chain_id: '42161'
                          name: Tether USDt
