name: Sync Rates API

# Run workflow for every push to the rates_api.yml file
on:
  push:
    branches:
      - main
    paths:
      - "openAPI/rates_api.yml"

jobs:
  sync-rates-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./openAPI/rates_api.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.DEFINITION_ID_RATES }}
